### ISSUE TITLE
Cluster reported as ready but has no nodes

### ISSUE THREAD

**Issue by RockScience** [gc3-uzh-ch/elasticluster#141]
I am using the following elasticluster configuration file:  

    [cloud/amazon-us-west-2]
    provider=ec2_boto
    ec2_url=https://ec2.us-west-2.amazonaws.com
    ec2_access_key=***********
    ec2_secret_key=***********
    ec2_region=us-west-2
    
    [login/ubuntu]
    image_user=ubuntu
    image_user_sudo=root
    image_sudo=True
    user_key_name=elasticluster
    user_key_private=~/.ssh/id_rsa
    user_key_public=~/.ssh/id_rsa.pub
    
    [setup/ansible-slurm]
    provider=ansible
    frontend_groups=slurm_master
    compute_groups=slurm_clients
    
    [cluster/slurm]
    cloud=amazon-us-west-2
    login=ubuntu
    setup_provider=ansible-slurm
    security_group=default
    # Ubuntu image
    image_id=ami-856ffeb5
    flavor=m1.small
    frontend_nodes=1
    compute_nodes=2
    ssh_to=frontend

I have created a ssh key pair on my local Ubuntu using 

    ssh-keygen -t rsa

Then imported the public key to Amazon under name 'elasticluster'

But then when starting the cluster I get the following error:

    $ elasticluster start slurm -n mycluster
    Starting cluster `mycluster` with 2 compute nodes.
    Starting cluster `mycluster` with 1 frontend nodes.
    (this may take a while...)
    ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
    ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
    ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
    ERROR:gc3.elasticluster:Could not connect to all the nodes of the cluster within the given timeout `600`.
    ERROR:gc3.elasticluster:Stopping node `compute001`, since we could not connect to it within the timeout.
    ERROR:gc3.elasticluster:Stopping node `compute002`, since we could not connect to it within the timeout.
    ERROR:gc3.elasticluster:Stopping node `frontend001`, since we could not connect to it within the timeout.
    Configuring the cluster.
    (this too may take a while...)
    Your cluster is ready!
    WARNING:gc3.elasticluster:preferred `ssh_to` `frontend` is empty: unable to get the choosen frontend node from that class.
    ERROR:gc3.elasticluster:Unable to get information on the frontend node: Unable to find a valid frontend: cluster has no nodes!
    
    Cluster name:     mycluster
    Frontend node: unknown
    - compute nodes: 0
    - frontend nodes: 0

**Comment by RockScience** [comment]
Thank you Nicolas for your answer. 
Indeed I checked by refreshing the AWS online console at the same time, and it seems that the 3 instances are first initiated (Although the instance state already indicates "Shutting Down" which is not a good sign):

![screenshot from 2015-01-05 17 36 57](https://cloud.githubusercontent.com/assets/5772226/5611453/d3d719b4-9501-11e4-9c94-83291cef212b.png)

But very quickly (few seconds) the Instances state switches to "Terminated"
![amazon_elasticluster_instances](https://cloud.githubusercontent.com/assets/5772226/5611341/834c65ae-9500-11e4-9b00-8004b6dda208.png)

Then there is a long moment with nothing happening and the rest of the error appears:

    ERROR:gc3.elasticluster:Could not connect to all the nodes of the cluster within the given timeout `600`.
    ERROR:gc3.elasticluster:Stopping node `compute001`, since we could not connect to it within the timeout.
    ERROR:gc3.elasticluster:Stopping node `compute002`, since we could not connect to it within the timeout.
    ERROR:gc3.elasticluster:Stopping node `frontend001`, since we could not connect to it within the timeout.
    Configuring the cluster.
    (this too may take a while...)
    Your cluster is ready!
    WARNING:gc3.elasticluster:preferred `ssh_to` `frontend` is empty: unable to get the choosen frontend node from that class.
    ERROR:gc3.elasticluster:Unable to get information on the frontend node: Unable to find a valid frontend: cluster has no nodes!
    
    Cluster name:     mycluster
    Frontend node: unknown
    - compute nodes: 0
    - frontend nodes: 0

And if I refresh the AWS console the 3 instances above are still there, still terminated.
Any hint what's going wrong? Could it be an issue with identification (my secret key) or in the SSL key pair?
I am surprised because if the instances can be first created then I would expect that amazon already recognizes me as a valid user...

**Comment by RockScience** [comment]
also

        (elasticluster)fred@machine1:~$ elasticluster list
        Traceback (most recent call last):
          File "/DOMAIN/users/fred/elasticluster/bin/elasticluster", line 9, in <module>
          load_entry_point('elasticluster==1.2', 'console_scripts', 'elasticluster')()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/main.py", line 177, in main
        app.run()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/cli/app.py", line 245, in run
        return self.post_run(returned)
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/cli/app.py", line 241, in run
        returned = self.main(*args)
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/main.py", line 162, in main
        return self.params.func()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/subcommands.py", line 70, in __call__
        return self.execute()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/subcommands.py", line 404, in execute
        clusters = repository.get_all()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/repository.py", line 153, in get_all
        clusters.append(self.get(cluster_file))
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/repository.py", line 167, in get
        cluster = pickle.load(storage)
        File "/usr/lib/python2.7/pickle.py", line 1378, in load
        return Unpickler(file).load()
        File "/usr/lib/python2.7/pickle.py", line 858, in load
        dispatch[key](self)
        File "/usr/lib/python2.7/pickle.py", line 880, in load_eof
        raise EOFError
        EOFError



        (elasticluster)fred@machine1:~$ elasticluster list-nodes clust3
        Traceback (most recent call last):
          File "/DOMAIN/users/fred/elasticluster/bin/elasticluster", line 9, in <module>
          load_entry_point('elasticluster==1.2', 'console_scripts', 'elasticluster')()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/main.py", line 177, in main
        app.run()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/cli/app.py", line 245, in run
        return self.post_run(returned)
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/cli/app.py", line 241, in run
        returned = self.main(*args)
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/main.py", line 162, in main
        return self.params.func()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/subcommands.py", line 70, in __call__
        return self.execute()
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/subcommands.py", line 494, in execute
        cluster = configurator.load_cluster(cluster_name)
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/conf.py", line 203, in load_cluster
        cluster = repository.get(cluster_name)
        File "/DOMAIN/users/fred/elasticluster/local/lib/python2.7/site-packages/elasticluster/repository.py", line 167, in get
        cluster = pickle.load(storage)
        File "/usr/lib/python2.7/pickle.py", line 1378, in load
        return Unpickler(file).load()
        File "/usr/lib/python2.7/pickle.py", line 858, in load
        dispatch[key](self)
        File "/usr/lib/python2.7/pickle.py", line 880, in load_eof
        raise EOFError
        EOFError

**Comment by nicolasbaer** [comment]
What version of elasticluster are you using? This looks like a bug we've already fixed.

**Comment by RockScience** [comment]
`$ elasticluster --version` returns 1.2

**Comment by nicolasbaer** [comment]
Could you please delete all files in the following folder `~/.elasticluster/storage/` and try to start a cluster again?

**Comment by RockScience** [comment]
Thanks Nicolas, I have done it but I still have the same error afterwards.

**Comment by nicolasbaer** [comment]
Could you please post your configuration file here, so I can try to reproduce the error. Please make sure to remove all sensitive data, such as your credentials.

**Comment by RockScience** [comment]
[cloud/amazon-us-west-2]
provider=ec2_boto
ec2_url=https://ec2.us-west-2.amazonaws.com
ec2_access_key=***
ec2_secret_key=***
ec2_region=us-west-2

[login/ubuntu]
image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/id_rsa
user_key_public=~/.ssh/id_rsa.pub

[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_clients

[cluster/slurm]
cloud=amazon-us-west-2
login=ubuntu
setup_provider=ansible-slurm
security_group=default
# Ubuntu image
image_id=ami-3d50120d
flavor=t2.micro
frontend_nodes=1
compute_nodes=2
ssh_to=frontend

**Comment by cocoy** [comment]
Same here, got the same problem with @RockScience  
Ubuntu 14.04
Python 2.7.6
elasticluster version 1.2

 ```
[cloud/amazon-us-east-1]
provider=ec2_boto
ec2_url=https://ec2.us-east-1.amazonaws.com
ec2_access_key=xxx
ec2_secret_key=xxx
ec2_region=us-east-1

[login/ubuntu]
image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=my-keypair
user_key_private=~/.ssh/id_rsa-my-keypair
user_key_public=~/.ssh/id_rsa-my-keypair.pub


[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_clients

[cluster/aws-slurm]
cloud=amazon-us-east-1
login=ubuntu
setup_provider=ansible-slurm
security_group=default
image_id=ami-74e27e1c
flavor=m1.small
frontend_nodes=1
compute_nodes=2
ssh_to=frontend
```
Can't list and terminate instances using the ```elasticluster``` commands

**Comment by RockScience** [comment]
ok, thanks.
is the traceback of error similar?

**Comment by cocoy** [comment]
yes same traceback, seems the problem is on the pickle file at the storage folder. I tried loading it manually using python cli. Probably at  save_update or somewhere :)

**Comment by RockScience** [comment]
I confirm I have a file `~/.elasticluster/storage/mycluster.pickle` that was created. But I don' know how to test this file or whether the issue is when writing/reading/executing it

**Comment by nicolasbaer** [comment]
I'll have a look at it this weekend. It looks like we're trying to store a cyclic reference into pickle.

**Comment by nicolasbaer** [comment]
Could you please try it again with the latest development version? I can't reproduce this error. You can find a short guide to install the development version here: https://github.com/gc3-uzh-ch/elasticluster#installing-the-development-version-from-github

**Comment by cocoy** [comment]
Ok after some test with the master branch, I got a working elasticluster on aws.
Output below:

```
(elasticluster)vagrant@vagrant-ubuntu-trusty-64:~/elasticluster$ elasticluster start aws-slurm -v
Starting cluster `aws-slurm` with 2 compute nodes.
Starting cluster `aws-slurm` with 1 frontend nodes.
(this may take a while...)
INFO:gc3.elasticluster:Starting node compute001.
INFO:gc3.elasticluster:Starting node compute002.
INFO:gc3.elasticluster:Starting node frontend001.
ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
INFO:gc3.elasticluster:_start_node: node has been started
INFO:gc3.elasticluster:_start_node: node has been started
INFO:gc3.elasticluster:_start_node: node has been started
INFO:gc3.elasticluster:Connection to node compute001 (xx.xx.xx.xx) successful.
INFO:gc3.elasticluster:Connection to node frontend001 (xx.xx.xx.xx) successful.
INFO:gc3.elasticluster:Connection to node compute002 (xx.xx.xx.xx) successful.
Configuring the cluster.
(this too may take a while...)

PLAY [Collecting facts] ******************************************************* 

GATHERING FACTS *************************************************************** 
ok: [compute002]
ok: [frontend001]
ok: [compute001]

TASK: [group_by key="$gc3group"] ********************************************** 
changed: [frontend001]

PLAY [GC3 master playbook] **************************************************** 
skipping: no hosts matched

... more output cut...

```
@RockScience  how is it going on your tests?

**Comment by RockScience** [comment]
I am not as lucky, I have followed instructions on http://elasticluster.readthedocs.org/en/latest/install.html#installing-from-github

It has replaced my version of elasticluster to `version 1.1-dev` and I have the same error when trying to launch a cluster. (I had version 1.2 before so I am a bit surprised)

@cocoy which version of elasticluster was installed from git on your machine?

**Comment by cocoy** [comment]
I  virtualenv and install from github. It's now  elasticluster   - 1.1-dev  

```
(elasticluster)vagrant@vagrant-ubuntu-trusty-64:~/elasticluster$ yolk -l
Babel           - 1.3          - active 
Jinja2          - 2.7.3        - active 
MarkupSafe      - 0.23         - active 
PyYAML          - 3.11         - active 
Python          - 2.7.6        - active development (/usr/lib/python2.7/lib-dynload)
ansible         - 1.8.2        - active 
argparse        - 1.2.1        - active development (/usr/lib/python2.7)
boto 2.35.1 has no metadata
configobj       - 5.0.6        - active 
ecdsa           - 0.11         - active 
elasticluster   - 1.1-dev      - active 
google-api-python-client - 1.3.1        - active 
httplib2        - 0.9          - active 
iso8601         - 0.1.10       - active 
mock            - 1.0.1        - active 
netaddr 0.7.13 has no metadata
netifaces       - 0.10.4       - active 
nose 1.3.4 has no metadata
oauth2client    - 1.4.6        - active 
oslo.config 1.6.0 has no metadata
oslo.i18n 1.3.0 has no metadata
oslo.serialization 1.2.0 has no metadata
oslo.utils 1.2.1 has no metadata
paramiko 1.15.2 has no metadata
pbr 0.10.7 has no metadata
pip 1.5.4 has no metadata
prettytable     - 0.7.2        - active 
pyCLI           - 2.0.3        - active 
pyasn1-modules  - 0.0.5        - active 
pyasn1          - 0.1.7        - active 
pycrypto        - 2.6.1        - active 
python-gflags   - 2.0          - active 
python-keystoneclient 1.0.0 has no metadata
python-novaclient 2.20.0 has no metadata
pytz 2014.10 has no metadata
requests 2.5.1 has no metadata
rsa             - 3.1.4        - active 
setuptools 2.2 has no metadata
simplejson      - 3.6.5        - active 
six 1.9.0 has no metadata
stevedore 1.2.0 has no metadata
uritemplate     - 0.6          - active 
voluptuous      - 0.8.7        - active 
wsgiref         - 0.1.2        - active development (/usr/lib/python2.7)
yolk            - 0.4.3        - active 
```

**Comment by nicolasbaer** [comment]
I just updated the version on our master branch to 1.3-dev. 
@RockScience i can't reproduce this error in the latest version. Maybe you could try again in a virtualenv to ensure that the downgrade of elasticluster does not result in any noise.

**Comment by RockScience** [comment]
ok thanks for upgrading the main branch. I will look at it and come back to you soon but I need first to get from my admin full access of my computer to do the additional tests.

**Comment by RockScience** [comment]
indeed I had installed elasticluster both using pip and git, so I cleaned elasticluster using the following commands:

```
sudo pip uninstall elasticluster
cd ~/
sudo rm -r elasticluster
```
Then reinstalled inside a virtualenv as follow:
```
virtualenv elasticluster
. elasticluster/bin/activate
cd elasticluster
git clone git://github.com/gc3-uzh-ch/elasticluster.git src
cd src
python setup.py install
```

**Comment by RockScience** [comment]
ok I cleaned elasticluster using the following commands:

```
sudo pip uninstall elasticluster
sudo rm -r ~/elasticluster
```
At this point 
```whereis elasticluster
and
elasticluster --version```
both return nothing

Then I re-installed elasticluster as follow:
```
sudo pip uninstall google-api-python-client
virtualenv elasticluster
. elasticluster/bin/activate
pip install google-api-python-client
pip install ansible
cd elasticluster
git clone git://github.com/gc3-uzh-ch/elasticluster.git src
cd src
python setup.py install
```

    elasticluster --version

returns 1.3dev

I have also made sure that `~/.elasticluster/storage/` is empty.

But then `elasticluster start slurm -n mycluster` gives the following time out

```
Starting cluster `mycluster2` with 2 compute nodes.
Starting cluster `mycluster2` with 1 frontend nodes.
(this may take a while...)
ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
ERROR:gc3.elasticluster:Apparently, Amazon does not compute the RSA key fingerprint as we do! We cannot check if the uploaded keypair is correct!
ERROR:gc3.elasticluster:Could not connect to all the nodes of the cluster within the given timeout `600`.
ERROR:gc3.elasticluster:Stopping node `compute001`, since we could not connect to it within the timeout.
ERROR:gc3.elasticluster:Stopping node `compute002`, since we could not connect to it within the timeout.
ERROR:gc3.elasticluster:Stopping node `frontend001`, since we could not connect to it within the timeout.
Configuring the cluster.
(this too may take a while...)
Your cluster is ready!
WARNING:gc3.elasticluster:preferred `ssh_to` `frontend` is empty: unable to get the choosen frontend node from that class.
ERROR:gc3.elasticluster:Unable to get information on the frontend node: Unable to find a valid frontend: cluster has no nodes!

Cluster name:     mycluster2
Cluster template: slurm
Default ssh to node: unknown
- compute nodes: 0
- frontend nodes: 0
```

**Comment by nicolasbaer** [comment]
Can you connect to the created instances using ssh?

**Comment by ajaceves** [comment]
I'm having the same problem here on version 1.3 dev.  Was this one ever solved?

**Comment by jinli-twoeightsix** [comment]
I'm also having the same problem on version 1.3 dev. Did you figured this out?

**Comment by riccardomurri** [comment]
@jinli-twoeightsix I cannot reproduce the error with the current GitHub "master" branch.  What exact error are you getting? If it has the version number "1.2" in it, your version 1.3.dev code was apparently not intalled correctly...

**Comment by jinli-twoeightsix** [comment]
@riccardomurri Thanks for your response. I removed the 1.3 dev version, and installed the 1.2.1rc1 version, but still have the same problem. I typed in the command: 
$elasticluster start gridengine
After copying and pasting a verification code, it says the authentication is successful, but after 10 minutes, I got the error messages:
2016-06-07 16:35:57 cs-6929-devshell-vm-6e6f75f5-4c91-4e5d-ab3c-ad47f8e1bd65-65 gc3.elasticluster[11933] ERROR Could not connect to all the nodes of the cluster within the given timeout `600`.
2016-06-07 16:35:57 cs-6929-devshell-vm-6e6f75f5-4c91-4e5d-ab3c-ad47f8e1bd65-65 gc3.elasticluster[11933] ERROR Stopping node `compute001`, since we could not connect to it within the timeout.
2016-06-07 16:35:57 cs-6929-devshell-vm-6e6f75f5-4c91-4e5d-ab3c-ad47f8e1bd65-65 gc3.elasticluster[11933] ERROR Stopping node `compute002`, since we could not connect to it within the timeout.
2016-06-07 16:35:58 cs-6929-devshell-vm-6e6f75f5-4c91-4e5d-ab3c-ad47f8e1bd65-65 gc3.elasticluster[11933] ERROR Stopping node `compute003`, since we could not connect to it within the timeout.2
016-06-07 16:35:58 cs-6929-devshell-vm-6e6f75f5-4c91-4e5d-ab3c-ad47f8e1bd65-65 gc3.elasticluster[11933] ERROR Stopping node `frontend001`, since we could not connect to it within the timeout.
Configuring the cluster.(this too may take a while...)Your cluster is ready!
2016-06-07 16:35:59 cs-6929-devshell-vm-6e6f75f5-4c91-4e5d-ab3c-ad47f8e1bd65-65 gc3.elasticluster[11933] WARNING preferred `ssh_to` `frontend` is empty: unable to get the choosen frontend node from that class.
2016-06-07 16:35:59 cs-6929-devshell-vm-6e6f75f5-4c91-4e5d-ab3c-ad47f8e1bd65-65 gc3.elasticluster[11933] ERROR Unable to get information on the frontend node: Unable to find a valid frontend: cluster has no nodes!

During the 10 minutes connecting period, 4 instances were established and I can use ssh to connect to the instances. But after 10 minutes and the error message pops up, the established 4 instances disappeared.

**Comment by riccardomurri** [comment]
> Thanks for your response. I removed the 1.3 dev version, and installed the 1.2.1rc1 version, but still have the same problem.

@jinli-twoeightsix Well no, it's not at all the same problem -- proof be that the error message in the title does not appear anywhere in the output you've posted...  Please open a new issue report for unrelated problems: this conversation should stay on-topic for those seeing the "load_entry_point" error in the subject.

**Comment by riccardomurri** [comment]
@jinli-twoeightsix Sorry I take that back -- this conversation *is* relevant, the title is skewed w.r.t. the contents.

**Comment by amyecampbell** [comment]
@riccardomurri has this been resolved ? @RockScience did reinstalling the development version solve your problem? 

Thanks !

**Comment by riccardomurri** [comment]
Here's my report after trying to reproduce the issue using ElastiCluster 1.3.dev
(currently: GitHub "master" branch); I have used the configuration posted by @cocoy 
above.

1. Starting nodes on AWS EC2 works;

2. Connection to the nodes via the public IP address also works, **provided**
   you enable TCP connections to port 22 from your home network (i.e., the
   computer where you are running the `elasticluster` command);

3. If SSH connections are not successful, then after 10 minutes `elasticluster`
   aborts and shuts down the nodes -- i.e. I cannot reproduce the problem
   mentioned in the title;

4. However, even if SSH connections are successful, an inventory file is *not*
   generated and the cluster is not set up. This is a bug, but it only affects
   the EC2 backend, as I can successfully spin up clusters on OpenStack and GCE.

This thread has changed title many times already and has accumulated information
and reports which are no longer relevant to the issues with the current code. I
would thus close it and open a separate issue for the problem at item 4. above.

**Comment by riccardomurri** [comment]
Please subscribe to the two issues referenced above if you're still interested.
