### ISSUE TITLE
Sudo reconfiguration needed for CentOS nodes

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#183]
Ansible playbooks all fail with CentOS nodes (at least when trying to build a SLURM cluster) because the `requiretty` setting in sudo isn't disabled.

See

https://bugzilla.redhat.com/show_bug.cgi?id=1020147

**Comment by riccardomurri** [comment]
This should now work with code from the branch `feature/forward-compatibility-with-ansible` (soon to be merged into `develop`), provided you turn "SSH pipelining" off:

        env ANSIBLE_SSH_PIPELINING=no elasticluster setup my-cluster # ...

**Comment by verdurin** [comment]
Was this ever merged? I can't see the branch, nor any indication of this fix in the `develop` log.

**Comment by riccardomurri** [comment]
As far as I can recall, the problem just is no longere there if you use Ansible >= 2.0 (which in turn requires ElastiCluster "develop")

**Comment by verdurin** [comment]
Just tried with the `develop` branch, and that still has the check for Ansible < 2.0...

**Comment by ChrisHad** [comment]
I've been using the develop branch and I still get the sudo issue even with Ansible >= 2.0.
I tried CentOS 7 and 6. 
Is there a way to enable more verbose output from ansible/elasticluster? I tried adding -vvv and creating an alias to 'ansible-playbooks -v' but it doesn't seem to do anything.

**Comment by riccardomurri** [comment]
In the "develop" branch, running `elasticluster -vvv` does actually run `ansible-playbook -vvv` -- what branch are you running elasticluster from?

**Comment by riccardomurri** [comment]
@verdurin The "develop" branch now requires Ansible >= 2.0 -- sorry I thought I had fixed this long ago so it went out of my radar ...

**Comment by ChrisHad** [comment]
I'm running the develop branch:
```
# On branch develop
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       setuptools-8.0-py2.7.egg
#       setuptools-8.0.zip
nothing added to commit but untracked files present (use "git add" to track)

```

I compared the output with and without -vvv and it doesn't seem to make any difference.
But I'm only concerned about the verbose as I was trying to workaround the sudo issue.

**Comment by riccardomurri** [comment]
Did you re-run `pip install -e .` after switching branches?

**Comment by ChrisHad** [comment]
I installed straight from develop branch and with "_python setup.py install_". 
I also tried " _pip install -e ._" but no difference. 
Just to be sure I removed the virtualenv and reinstalled as well.
Error output when starting cluster:

```
TASK [setup] *******************************************************************
fatal: [compute002]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: sorry, you must have a tty to run sudo\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
fatal: [compute001]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: sorry, you must have a tty to run sudo\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
fatal: [frontend001]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: sorry, you must have a tty to run sudo\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/home/xxxxx/elasticluster/share/elasticluster/providers/ansible-playbooks/site.retry

PLAY RECAP *********************************************************************
compute001                 : ok=0    changed=0    unreachable=0    failed=1   
compute002                 : ok=0    changed=0    unreachable=0    failed=1   
frontend001                : ok=0    changed=0    unreachable=0    failed=1   

2016-04-22 13:19:37 test.novalocal gc3.elasticluster[950] ERROR Command `ansible-playbook` failed with exit code 2.
2016-04-22 13:19:37 test.novalocal gc3.elasticluster[950] ERROR Check the output lines above for additional information on this error.
2016-04-22 13:19:37 test.novalocal gc3.elasticluster[950] ERROR The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup` or fix the playbooks.
2016-04-22 13:19:37 test.novalocal gc3.elasticluster[950] WARNING Cluster `slurm` not yet configured. Please, re-run `elasticluster setup slurm` and/or check your configuration
```

**Comment by ChrisHad** [comment]
For some strange reason when setting the ANSIBLE_KEEP_REMOTE_FILES=1 it tries to run most of the tasks but fails because in '_elasticluster/share/elasticluster/providers/ansible-playbooks/roles/common/vars/main.yml_' ansible_distribution returns RedHat which is not one of the possible values.

After changing the above trying to download slurm fails since the latest version is 15.08.10 and not 15.08.4 which is the version in roles/slurm.yml.
The rpmbuild command then builds an rpm named differently from the file in roles/slurm/tasks/main.yml.
Even after fixing the above issues the rpms fail to install as the package slurm-slurmdbd-direct should be slurm-slurmdb-direct. Then there's an issue with starting the slurm service which I haven't troubleshooted yet:

`Apr 24 23:17:29 frontend001 sudo[19106]: centos : TTY=pts/0 ; PWD=/home/centos ; USER=root ; COMMAND=/bin/systemctl start slurm.se
Apr 24 23:17:29 frontend001 systemd[1]: Starting LSB: slurm daemon management...
Apr 24 23:17:30 frontend001 slurmctld[19115]: error: MaxJobId can not exceed 0x7fffffff, resetting value
Apr 24 23:17:30 frontend001 slurm[19109]: starting slurmctld: [  OK  ]
Apr 24 23:17:30 frontend001 slurmctld[19118]: fatal: You are running with a database but for some reason we have no TRES from it.
Apr 24 23:17:30 frontend001 systemd[1]: PID file /var/run/slurmctld.pid not readable (yet?) after start.
Apr 24 23:17:30 frontend001 systemd[1]: slurm.service never wrote its PID file. Failing.
Apr 24 23:17:30 frontend001 systemd[1]: Failed to start LSB: slurm daemon management.
Apr 24 23:17:30 frontend001 systemd[1]: Unit slurm.service entered failed state.
`

**Comment by verdurin** [comment]
@ChrisHad: Maybe worth mentioning that I'm working on updating the Slurm playbook in #215.

It uses my Copr builds of Slurm. There is still a problem because the SSH authentication between the frontend node and the compute nodes is broken, and I think I nneed to rebase it with the develop branch anyway.

**Comment by verdurin** [comment]
@riccardomurri: I submitted a fix for the Ansible 2.0 part in #238.

**Comment by riccardomurri** [comment]
The "requiretty" issue is still there as of Ansible 2.0; the only workaround seems to be to turn "ssh pipelining" off.  I think that the only thing I can do is to mention the workaround in the ElastiCluster documentation: http://elasticluster.readthedocs.io/en/latest/troubleshooting.html#id3

Would this be an acceptable resolution of this issue?

**Comment by verdurin** [comment]
@riccardomurri - the workaround does indeed work around the problem for me, so that is acceptable, in default of a cleaner fix.

**Comment by riccardomurri** [comment]
Thanks, I'll close this then -- feel free to reopen if you find the resolution unsatisfactory or if there are any news.
