### ISSUE TITLE
Support use of SSH `ProxyCommand` to connect to cluster nodes

### ISSUE THREAD

**Issue by Smahane** [gc3-uzh-ch/elasticluster#510]
Hi,
I created a cluster in GCE with elasticluster as a test and I'm facing some difficulties. 

When i run : `elasticluster` start --name clustertest `redhatslurmcluster`
5 total nodes are successfully created in GCE and the clustertest.yaml contains the right information including the ip addresses for each node.  However, elasticluster believes that the nodes were created without an ip address and it fails to finish the setup (can't  even ssh to the cluster).

Error I get:
```
gc3.elasticluster[417952] ERROR Some nodes of the cluster were unreachable w
gc3.elasticluster[417952] WARNING Ignoring node `frontend001`: No IP address
gc3.elasticluster[417952] WARNING Ignoring node `compute001`: No IP address.
gc3.elasticluster[417952] WARNING Ignoring node `compute002`: No IP address.
gc3.elasticluster[417952] WARNING Ignoring node `compute003`: No IP address.
gc3.elasticluster[417952] WARNING Ignoring node `compute004`: No IP address.
```

Where could be the problem please?  Thank you

Here is my config file which works:
```
[cloud/google]
provider=google
gce_client_id=**************
gce_client_secret=*****************
gce_project_id=****************
noauth_local_webserver=True

[login/google]
image_user=***********
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/id_rsa
user_key_public=~/.ssh/id_rsa.pub

[setup/slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_worker
submit_groups=slurm_submit,glusterfs_client
global_var_multiuser_cluster=yes


[cluster/redhatslurmcluster]
cloud=google
login=google
security_group=default
image_id=https://www.googleapis.com/compute/v1/projects/rhel-cloud/global/images/rhel-7-v20171129
boot_disk_type=pd-ssd
boot_disk_size=20
flavor=n1-standard-1
setup=slurm
frontend_nodes=1
compute_nodes=4
compute_nodes_min=2
ssh_to=frontend
```

![image](https://user-images.githubusercontent.com/5471356/33968695-3163f72c-e01e-11e7-8b77-96dfd7817de7.png)

**Comment by riccardomurri** [comment]
Confirmed, I get the same result. Will try to investigate tomorrow.

**Comment by riccardomurri** [comment]
As a simple workaround, you can log in to compute nodes from the ElastiCluster machine with::

        elasticluster ssh mycluster -n compute123

**Comment by riccardomurri** [comment]
This is the only related error I could find in the logs::

        sshd[22261]: Did not receive identification string from 10.132.0.4 port 38536

**Comment by riccardomurri** [comment]
Actually, there is a hint that the problem is client-side::

```
$ ssh compute001
could not open any host key
ssh_keysign: no reply
sign using hostkey ecdsa-sha2-nistp256 SHA256:DJ6B7Y13moKsgE7S8QjDFIxZ4m6/P4IywWbN5o9DRTE failed
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,hostbased).
```

**Comment by riccardomurri** [comment]
So, it looks like the problem is with SSH host-based authentication.

Using the SSH agent with the key that was used to build the cluster
yields the expected results (run the following on the machine where
you run ElastiCluster)::

0. Start an SSH agent::

```sh
if [ -z "$SSH_AUTH_SOCK" ]; then eval $(ssh-agent -s); fi
```

1. Load the SSH key into the agent (must match what is `user_ssh_key_private` in the `[login/goole]` section of the config file)::

```sh
# adjust the following path according to config file
ssh-add ~/.ssh/google-compute-engine
```

2. Log in to the cluster, propagating the agent identities

```sh
elasticluster ssh mycluster -- -o forwardagent=yes
```

**Comment by Smahanita** [comment]
@riccardomurri I didn't expect a response this fast. So thank you so much for that.

I did try the above and I'm getting an error:
`gc3.elasticluster[446878] ERROR No IP address known for node frontend001`

Here is what i did. 
```
 bash-4.2$ history 5
  503  history 10
  504  if [ -z "$SSH_AUTH_SOCK" ]; then eval $(ssh-agent -s); fi
  505   ssh-add ~/.ssh/id_rsa
  506  elasticluster ssh mycluster -- -o forwardagent=yes
```
So this is mainly a firewall network issue?

**Comment by riccardomurri** [comment]
So it looks this is a problem with RHEL7 (or possibly recent OpenSSH),
which attempts to remove set-UID-to-root permission from a number of
system files, including `/usr/libexec/openssh/ssh-keysign` (which is
essential for getting SSH host-based authentication to work).  So the
problem is: SSH host keys are only readable by `root`, but RHEL7.4
removed the set-UID bit from `ssh-keysign` making it instead member of
a group `ssh_keys`.

Hence, with the default configuration, `ssh-keysign` cannot read the
host keys so host-based authentication fails.

In order to get host-based authentication to work, one must either
give back the set-root-UID capability to `ssh-keysign`, or make the
SSH host keys readable by group `ssh_keys`.  The latter can be done
on the whole cluster with the following commands::

        pdsh -a sudo chmod g+r /etc/ssh/ssh_host_*
        pdsh -a sudo chgrp ssh_keys /etc/ssh/ssh_host_*

I'll patch the ElastiCluster main playbooks in the following days
(it's getting late here now).

**Comment by riccardomurri** [comment]
@Smahanita Uhmmm... sorry -- it seems that I had been debugging a different issue that the one you reported :-/ 

Using your configuration, I can get a cluster up and running regularly -- so yes maybe it's just the security group that is not allowing connections from your IP address?  Can you destroy the cluster `elasticluster stop mycluster` and then post the output of `elasticluster -vvv start mycluster` (**watch out for passwords or other sentive info in the output**).

**Comment by Smahanita** [comment]
I think is it a security group. When i ran:
elasticluster -vvv --name mycluster ....

I get the error:
```
gc3.elasticluster[448571] DEBUG Trying to connect to host compute003 (35.225.60.113)
gc3.elasticluster[448571] DEBUG Host compute003 (35.225.60.113) not reachable: timed out.
gc3.elasticluster[448571] DEBUG Trying to connect to host compute001 (35.226.218.101)
gc3.elasticluster[448571] DEBUG Host compute001 (35.226.218.101) not reachable: timed out.
gc3.elasticluster[448571] DEBUG Trying to connect to host compute002 (35.225.10.58)
gc3.elasticluster[448571] DEBUG Host compute002 (35.225.10.58) not reachable: timed out.
gc3.elasticluster[448571] DEBUG Trying to connect to host frontend001 (35.224.243.133)
gc3.elasticluster[448571] DEBUG Host frontend001 (35.224.243.133) not reachable: timed out.
gc3.elasticluster[448571] DEBUG Trying to connect to host compute004 (35.202.243.87) ....
```
When i try to ssh to any of the nodes created above, I can't.

I had to manually add the ip address of the frontend001 node  to ~/.ssh/config to enable the Socks connection with ForwardAgent.
Then run 
 gcloud compute --project "name" ssh --zone "us-central1-a" "mycluster-frontend001"

Which setup the ssh connection and allowed me to connect to the node.

How do I incorporate this with elasticluster? It obvious now that it has to go through sock5 to setup the cluster.

**Comment by riccardomurri** [comment]
> How do I incorporate this with elasticluster? It obvious now that it has to go through sock5 to setup the cluster.

Hmmm... well, the first question would be: why does it work out of the box for me, whereas you need to go through this special setup?  Is the SOCKS5 proxy something that is running at your home site, or did you set it up for your GCE project?

**Comment by Smahanita** [comment]
@riccardomurri  no it wasn't set for GCE project.  SOCKS5 proxy is running at our lab. We tried few things and we couldn't find any other way to ssh to external environments without going through it.  I hope elasticluster implementation has such a network setup in mind.

**Comment by riccardomurri** [comment]
@Smahanita I am afraid I have 0 experience with SOCKS proxies.  If you can describe the procedure you have to apply in order to SSH to an external computer, I can see what I can do to make ElastiCluster support it.

**Comment by riccardomurri** [comment]
For the moment, a simple workaround could be this:

* start a tiny VM on GCE
* connect to this tiny VM via SSH and install ElastiCluster there
* use the tiny VM to deploy your cluster -- there should be no SOCKS/firewall issue from the VM to the cluster, provided you place both in the same security group on GCE (or configure rules accordingly)

**Comment by Smahanita** [comment]
@riccardomurri  thank you for all the suggestions. The process I do to be able to ssh to an external  machine is just adding the hostname IP to the ~/.ssh/config (I'm not very sure what all these mean but it works) : 

```
Host 111.111.111.11
        ProxyCommand ~/bin/connect -5 -S proxy.$address:$port %h %p  
ForwardAgent yes
```

Regarding your other suggestion, I  installed elasticluster on a GCE vm and created a cluster from there with no issue. However, I'm not able to ssh to cluster nodes from the front node but can ssh from each others:

      frontend001 ssh to computenode1 : fails
      computenodeX ssh to computenodeY: passes
      computenodeX ssh to frontend001 :fails
 
Shouldn't the sets up of the  passwordless trust between all pairs of nodes  be done by elasticluster during the creation of the cluster?

**Comment by riccardomurri** [comment]
> The process I do to be able to ssh to an external machine is just adding *[...]* to the ~/.ssh/config

I see, so you would need to have the equivalent of SSH's
`ProxyCommand` to ElastiCluster.  I'll see what I can do:
ElastiCluster does not use SSH directly, rather it uses a Python
reimplementation of the SSH protocol, called Paramiko; I have to check
whether Paramiko supports the equivalent of OpenSSH's `ProxyCommand`.


> However, I'm not able to ssh to cluster nodes from the front node but can ssh from each others:

This bug was fixed in commit
https://github.com/gc3-uzh-ch/elasticluster/commit/97f83e3a543f51acf33f2708876fd61d82032124
-- can you please update your ElastiCluster to the latest "master" and
retry?  (You need to run `elasticluster setup` to fix existing
clusters; newly-spawned clusters will not have the issue).

**Comment by Smahanita** [comment]
@riccardomurri  I have installed the latest elasticluster but im still unable to ssh to the compute nodes from the head node:

```
[user@frontend001 ~]$ ssh mycluster-compute001
The authenticity of host 'mycluster-compute001 (10.128.0.2)' can't be established.
ECDSA key fingerprint is SHA256:6MgUSZNxEKrcEx+TaROPyq/iYvwZt3gkFq/XG0O7ECQ.
ECDSA key fingerprint is MD5:ff:9d:50:13:89:32:60:ec:05:79:30:79:6a:0c:19:b6.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'mycluster-compute001' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```
Here is what i did:
```
pip uninstall elasticluster
git clone https://github.com/gc3-uzh-ch/elasticluster.git
pip install -e .
elasticluster start clustergold -n mycluster
elasticluster ssh mycluster
```
Ideas please? Anything im missing here? I'm running everything from an instance I created on Google Cloud
Thank you,

**Comment by riccardomurri** [comment]
Are you using the same configuration as in [the initial comment](https://github.com/gc3-uzh-ch/elasticluster/issues/510#issue-281940012) ?

**Comment by riccardomurri** [comment]
I can confirm that cross-cluster SSH does not work in RHEL.

It seems this was a deliberate choice of Red Hat: they disabled host-based authentication.  I'll see whether I can undo that configuration.

**Comment by riccardomurri** [comment]
It look like the solution is already in [this earlier comment](https://github.com/gc3-uzh-ch/elasticluster/issues/510#issuecomment-351832450). I still need to patch the playbooks to implement it by default.

**Comment by riccardomurri** [comment]
Can you please try restarting the SSH daemon?

    sudo service sshd restart

**Comment by riccardomurri** [comment]
Can you please try restarting the SSH daemon (on all nodes)?

    sudo service sshd restart

Does this fix the issue?

**Comment by riccardomurri** [comment]
@Smahanita Should *really* be fixed in the latest "master" branch.  Can you please update and retry?

**Comment by Smahanita** [comment]
I got the latest master and i ran 'elasticluster setup mycluster' but It still didn't work

Also, any other way to update elasticluster? for now, I uninstall, clone latest, and install again.

Thank you

**Comment by riccardomurri** [comment]
> I got the latest master and i ran 'elasticluster setup mycluster' but It still didn't work

This time I cannot reproduce your problem: it *does* work for me...

> Also, any other way to update elasticluster?

Run `git pull` in the source code directory.

**Comment by riccardomurri** [comment]
Can you please run `elasticluster -vvv start mycluster` and post the complete output?  (Here or upload to a pastebin and copy the URL here.)

**Comment by Smahanita** [comment]
@riccardomurri  it works now! I'm not sure what was wrong. I think it was my private and public keys maybe? I regenerated them, deleted the cluster, and ran `elasticluster` start clustergold -n mycluster`

It's working now. Thanks a lot.

**Comment by riccardomurri** [comment]
> It's working now.

Good to know :-) All is well that ends well.

I have some ideas for the SSH proxy issue, but I don't have time to implement now -- I guess the workaround of running an ElastiCluster VM on GCP works for you?

**Comment by Smahanita** [comment]
@riccardomurri  the work around of using GCP is temporarily solving the problem now since i'm just doing a demo and experimenting different approaches of creating a cluster. So far Elasticluster is my favorite option. It would be great to solve the proxy issue when possible. I'm hoping to use Elasticlaster with other cloud providers as well and it will be more convenient for our environment users to set it up locally  in our system vs on the cloud. thank you

**Comment by riccardomurri** [comment]
> It would be great to solve the proxy issue when possible.

It's definitely on my TO-DO list, but I am not sure when I will have time to work on it.
Give me a wake up call here when you have deadlines approaching for this.

**Comment by riccardomurri** [comment]
@Smahanita I have pushed code to fix the "proxy command" stuff in https://github.com/gc3-uzh-ch/elasticluster/pull/523 -- it works for me, can you please test it and tell me if it works?

You would need to add a line like the following to your `[cluster/...]` configuration stanza when you run from inside your home network (as opposed to running `elasticluster` from a small VM in GCE):

        [cluster/mycluster]
        # ...everything stays the same, just add:
        ssh_proxy_command=~/bin/connect -5  -S proxy.$address:$port %%%h %%%p

*Note:* yes, you need `%%%h` instead of `%h` and `%%%p` instead of `%p`! Cf. your comment https://github.com/gc3-uzh-ch/elasticluster/issues/510#issuecomment-353486684

**Comment by riccardomurri** [comment]
Sorry, it's `%%h` and `%%p` (two `%`'s not three). I will edit the text in the comment above.
